Digi XBee(R) ANSI C Host Library: HAL: Freescale/Codewarrior (Programmable XBee)
HAL: Freescale/Codewarrior (Programmable XBee)
Hardware Abstraction Layer (HAL)
Freescale HCS08 platform (XBee Programmable using CodeWarrior).
Files
file platform_config.h
This file is automatically included by xbee/platform.h.
file xbee_platform_hcs08.c
Platform-specific functions for use by the XBee Driver on Freescale HCS08 platform.
file xbee_serial_hcs08.c
Serial Interface for Programmable XBee Module (Freescale HCS08 Platform).
Data Structures
struct xbee_serial_t
Macros
#define XBEE_CW6
#define __FUNCTION__ "xbee"
#define LITTLE_ENDIAN 1234
#define BIG_ENDIAN 4321
#define PDP_ENDIAN 3412
#define BYTE_ORDER BIG_ENDIAN
#define _f_memcpy memcpy
#define _f_memset memset
#define INT16_C(x) (x)
#define UINT16_C(x) (x ## U)
#define INT32_C(x) (x ## L)
#define UINT32_C(x) (x ## UL)
#define PRId16 "d"
#define PRIu16 "u"
#define PRIx16 "x"
#define PRIX16 "X"
#define FAR
#define SERIAL_PORT_SCI1 1
#define SERIAL_PORT_SCI2 2
#define ZCL_TIME_EPOCH_DELTA 0
#define HAVE_SWAP_FUNCS 1
#define xbee_seconds_timer() (SEC_TIMER)
#define xbee_millisecond_timer() (MS_TIMER)
#define XBEE_MS_TIMER_RESOLUTION 4
#define RTS_ASSERT_BYTES 8
#define _FLAG_FLOW(x) (x)
#define _FLAG_RTS(x) (x << 2)
#define _FLAG_FLOW_HOST _FLAG_FLOW(1)
#define _FLAG_FLOW_EMBER _FLAG_FLOW(2)
#define _FLAG_RTS_HOST _FLAG_RTS(1)
#define _FLAG_RTS_EMBER _FLAG_RTS(2)
#define LOOPBACK_OFF (0*SCI1C1_LOOPS_MASK)
#define LOOPBACK_ON (1*SCI1C1_LOOPS_MASK)
#define UART_OFF_DURING_WAIT (1*SCI1C1_SCISWAI_MASK)
#define UART_ON_DURING_WAIT (0*SCI1C1_SCISWAI_MASK)
#define LOOPBACK_TWO_WIRE (0*SCI1C1_RSRC_MASK)
#define LOOPBACK_ONE_WIRE (1*SCI1C1_RSRC_MASK)
#define CHARACTER_8BIT (0*SCI1C1_M_MASK)
#define CHARACTER_9BIT (1*SCI1C1_M_MASK)
#define WAKEUP_IDLE_LINE (0*SCI1C1_WAKE_MASK)
#define WAKEUP_ADDRESS_MARK (1*SCI1C1_WAKE_MASK)
#define IDLE_COUNT_AFTER_START_BIT (0*SCI1C1_ILT_MASK)
#define IDLE_COUNT_AFTER_STOP_BIT (1*SCI1C1_ILT_MASK)
#define PARITY_OFF (0*SCI1C1_PE_MASK)
#define PARITY_ON (1*SCI1C1_PE_MASK)
#define PARITY_EVEN (0*SCI1C1_PT_MASK)
#define PARITY_ODD (1*SCI1C1_PT_MASK)
#define RX_WAKEUP_CONTROL_OFF (0*SCI1C2_RWU_MASK)
#define RX_WAKEUP_CONTROL_ON (1*SCI1C2_RWU_MASK)
#define RX_DISABLE (0*SCI1C2_RE_MASK)
#define RX_ENABLE (1*SCI1C2_RE_MASK)
#define TX_DISABLE (0*SCI1C2_TE_MASK)
#define TX_ENABLE (1*SCI1C2_TE_MASK)
#define IDLE_INTERRUPT_DISABLE (0*SCI1C2_ILIE_MASK)
#define IDLE_INTERRUPT_ENABLE (1*SCI1C2_ILIE_MASK)
#define RX_INTERRUPT_DISABLE (0*SCI1C2_RIE_MASK)
#define RX_INTERRUPT_ENABLE (1*SCI1C2_RIE_MASK)
#define TX_COMPLETE_INTERRUPT_DISABLE (0*SCI1C2_TCIE_MASK)
#define TX_COMPLETE_INTERRUPT_ENABLE (1*SCI1C2_TCIE_MASK)
#define TX_BUFFER_READY_INTERRUPT_DISABLE (0*SCI1C2_TIE_MASK)
#define TX_BUFFER_READY_INTERRUPT_ENABLE (1*SCI1C2_TIE_MASK)
#define RX_PARITY_ERROR_INTERRUPT_DISABLE (0*SCI1C3_PEIE_MASK)
#define RX_PARITY_ERROR_INTERRUPT_ENABLE (1*SCI1C3_PEIE_MASK)
#define RX_FRAMING_ERROR_INTERRUPT_DISABLE (0*SCI1C3_FEIE_MASK)
#define RX_FRAMING_ERROR_INTERRUPT_ENABLE (1*SCI1C3_FEIE_MASK)
#define RX_NOISE_ERROR_INTERRUPT_DISABLE (0*SCI1C3_NEIE_MASK)
#define RX_NOISE_ERROR_INTERRUPT_ENABLE (1*SCI1C3_NEIE_MASK)
#define RX_OVERRUN_INTERRUPT_DISABLE (0*SCI1C3_ORIE_MASK)
#define RX_OVERRUN_INTERRUPT_ENABLE (1*SCI1C3_ORIE_MASK)
#define TX_DATA_NORMAL (0*SCI1C3_TXINV_MASK)
#define TX_DATA_INVERTED (1*SCI1C3_TXINV_MASK)
#define ONE_WIRE_RX_MODE (0*SCI1C3_TXDIR_MASK)
#define ONE_WIRE_TX_MODE (1*SCI1C3_TXDIR_MASK)
#define RX_BREAK_DETECT_10_BITS (0*SCI1S2_LBKDE_MASK)
#define RX_BREAK_DETECT_11_BITS (1*SCI1S2_LBKDE_MASK)
#define TX_BREAK_10_BITS (0*SCI1S2_BRK13_MASK)
#define TX_BREAK_13_BITS (1*SCI1S2_BRK13_MASK)
#define RX_IDLE_DETECT_OFF (0*SCI1S2_RWUID_MASK)
#define RX_IDLE_DETECT_ON (1*SCI1S2_RWUID_MASK)
#define RX_DATA_INVERTED (1*SCI1S2_RXINV_MASK)
#define RX_DATA_NORMAL (0*SCI1S2_RXINV_MASK)
#define XBEE_SER_CHECK(ptr)
#define XBEE_SER_CHECK_RTS(s)
#define SCIxC1_DEFAULT
#define SCIxC3_DEFAULT
#define SCIxS2_DEFAULT
#define SCIxC2_DEFAULT
#define _ISR_RTS(port, pin)
Typedefs
typedef signed char int8_t
typedef unsigned char uint8_t
typedef int int16_t
typedef unsigned int uint16_t
typedef long int32_t
typedef unsigned long uint32_t
typedef unsigned char uint_fast8_t
typedef signed char int_fast8_t
typedef uint8_t bool_t
Functions
void xbee_reset_radio (struct xbee_dev_t *xbee, bool_t asserted)
Function to pass to xbee_dev_init() to control the EM250's /RESET pin on PTCD4.
uint32_t() xbee_seconds_timer (void)
Platform-specific function to return the number of elapsed seconds.
uint32_t() xbee_millisecond_timer (void)
Platform-specific function to return the number of elapsed milliseconds.
uint16_t swap16 (uint16_t value)
Swap the byte order of a 16-bit value.
uint32_t swap32 (uint32_t value)
Swap the byte order of a 32-bit value.
bool_t xbee_ser_invalid (xbee_serial_t *serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
const char * xbee_ser_portname (xbee_serial_t *serial)
Returns a human-readable string describing the serial port.
int xbee_ser_write (xbee_serial_t *serial, const void FAR *buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
int xbee_ser_read (xbee_serial_t *serial, void FAR *buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
int xbee_ser_putchar (xbee_serial_t *serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
int xbee_ser_getchar (xbee_serial_t *serial)
Reads a single character from the XBee serial port serial.
int xbee_ser_tx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_flush (xbee_serial_t *serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
int xbee_ser_rx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_flush (xbee_serial_t *serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
int xbee_ser_baudrate (xbee_serial_t *serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
int xbee_ser_open (xbee_serial_t *serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
int xbee_ser_close (xbee_serial_t *serial)
Close the serial port attached to XBee serial port serial.
int xbee_ser_break (xbee_serial_t *serial, bool_t enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
int xbee_ser_flowcontrol (xbee_serial_t *serial, bool_t enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
int xbee_ser_set_rts (xbee_serial_t *serial, bool_t asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
int xbee_ser_get_cts (xbee_serial_t *serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
xbee_cbuf_putch (EMBER_SERIAL_PORT.rxbuf, SCI2D)
This is the ISR for receiving data on the SCI2 serial port, which is connected to the Ember radio on the Programmable XBee.
_ISR_RTS (EMBER, PTCD_PTCD1)
Variables
xbee_serial_t HOST_SERIAL_PORT
xbee_serial_t EMBER_SERIAL_PORT
xbee_serial_t HOST_SERIAL_PORT = { 0, SERIAL_PORT_SCI1 }
xbee_serial_t EMBER_SERIAL_PORT = { 0, SERIAL_PORT_SCI2 }
uint8_t _flags = 0
Detailed Description
Freescale HCS08 platform (XBee Programmable using CodeWarrior).
Macro Definition Documentation
#define _ISR_RTS (port, pin)
Value:
if ((_flags & (_FLAG_FLOW_ ## port | _FLAG_RTS_ ## port)) ==                \
                        (_FLAG_FLOW_ ## port | _FLAG_RTS_ ## port)                  \
        && xbee_cbuf_free( port ## _SERIAL_PORT.rxbuf) < RTS_ASSERT_BYTES)  \
    { _flags &= ~_FLAG_RTS_ ## port; pin = 1; }
#define SCIxC1_DEFAULT
Value:
LOOPBACK_OFF | LOOPBACK_TWO_WIRE | UART_OFF_DURING_WAIT \
                | CHARACTER_8BIT | WAKEUP_IDLE_LINE | IDLE_COUNT_AFTER_START_BIT \
                | PARITY_OFF | PARITY_EVEN
#define SCIxC2_DEFAULT
Value:
RX_WAKEUP_CONTROL_OFF | RX_ENABLE | TX_ENABLE \
                | RX_INTERRUPT_ENABLE | IDLE_INTERRUPT_DISABLE \
                | TX_COMPLETE_INTERRUPT_DISABLE \
                | TX_BUFFER_READY_INTERRUPT_DISABLE
#define SCIxC3_DEFAULT
Value:
TX_DATA_NORMAL | RX_PARITY_ERROR_INTERRUPT_DISABLE \
                | RX_FRAMING_ERROR_INTERRUPT_DISABLE \
                | RX_NOISE_ERROR_INTERRUPT_DISABLE \
                | RX_OVERRUN_INTERRUPT_DISABLE | ONE_WIRE_RX_MODE
#define SCIxS2_DEFAULT
Value:
RX_BREAK_DETECT_10_BITS | TX_BREAK_10_BITS \
                | RX_IDLE_DETECT_OFF | RX_DATA_NORMAL
#define XBEE_SER_CHECK_RTS (s)
Value:
(((_flags >> (s->port - 1)) & (_FLAG_FLOW(1) | _FLAG_RTS(1))) \
                                                                            == _FLAG_FLOW(1))
Function Documentation
uint16_t swap16 (uint16_t value)
Swap the byte order of a 16-bit value.
Parameters
[in] value value to swap
Returns
new 16-bit value with opposite endianness of value
uint32_t swap32 (uint32_t value)
Swap the byte order of a 32-bit value.
Parameters
[in] value value to swap
Returns
new 32-bit value with opposite endianness of value
xbee_cbuf_putch (EMBER_SERIAL_PORT. rxbuf, SCI2D)
This is the ISR for receiving data on the SCI2 serial port, which is connected to the Ember radio on the Programmable XBee.
Make sure the .prm file for the project contains the following line:
 VECTOR ADDRESS 0x0000F1D2  vSci2Rx
Referenced by xbee_ser_get_cts().
uint32_t() xbee_millisecond_timer (void)
Platform-specific function to return the number of elapsed milliseconds.
OK for this counter to rollover. Used for timing and should have a resolution of at least 60ms.
Rabbit has 1ms resolution.
HCS08 has 4ms resolution.
DOS has 18 ticks/second (55.55ms resolution)
(Function name wrapped in parentheses so platforms can use a macro function of the same name.)
Returns
Number of elapsed milliseconds.
See also
XBEE_MS_TIMER_RESOLUTION
uint32_t() xbee_seconds_timer (void)
Platform-specific function to return the number of elapsed seconds.
On some platforms, this is the equivalent of an "uptime".
On other platforms, it may reflect the value of the RTC, which might not be synchronized with a time server and might include leap seconds.
Regardless, it should consistently report elapsed time and not jump on clock synchronization.
In addition to determining timeouts, the ZCL Time Cluster makes use of it to report current time.
(Function name wrapped in parentheses so platforms can use a macro function of the same name.)
Returns
Number of elapsed seconds.
int xbee_ser_baudrate (xbee_serial_t * serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_open(), xbee_ser_close(), xbee_ser_break()
References EINVAL, and EIO.
Referenced by xbee_ser_open().
int xbee_ser_break (xbee_serial_t * serial, bool_t enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
Parameters
[in] serial XBee serial port
[in] enabled Set to 1 to start the break or 0 to end the break (and resume transmitting).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_close()
int xbee_ser_close (xbee_serial_t * serial)
Close the serial port attached to XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 closed serial port
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_baudrate(), xbee_ser_break()
int xbee_ser_flowcontrol (xbee_serial_t * serial, bool_t enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] enabled Set to 0 to disable flow control or non-zero to enable flow control.
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_set_rts(), xbee_ser_get_cts()
References xbee_cbuf_free(), and xbee_ser_set_rts().
int xbee_ser_get_cts (xbee_serial_t * serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Note that this function doesn't return the value of the pin – it returns whether it's asserted (i.e., clear to send to the XBee serial port) or not.
Parameters
[in] serial XBee serial port
Return values
1 it's clear to send
0 it's not clear to send
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_set_rts()
References EINVAL, and xbee_cbuf_putch().
int xbee_ser_getchar (xbee_serial_t * serial)
Reads a single character from the XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0-255 character read from XBee serial port
-ENODATA There aren't any characters in the read buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References ENODATA, xbee_cbuf_free(), xbee_cbuf_getch(), and xbee_ser_set_rts().
bool_t xbee_ser_invalid (xbee_serial_t * serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
Confirms that it is non-NULL and is set to a valid port.
Parameters
[in] serial XBee serial port
Return values
1 serial is not a valid XBee serial port
0 serial is a valid XBee serial port
int xbee_ser_open (xbee_serial_t * serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_baudrate(), xbee_ser_close(), xbee_ser_break()
References EINVAL, and xbee_ser_baudrate().
const char* xbee_ser_portname (xbee_serial_t * serial)
Returns a human-readable string describing the serial port.
For example, on a Windows machine this will be "COM1" or "COM999". On a Rabbit, it will be a single letter, "A" through "F". On Freescale HCS08, it will be something like "SCI1" or "SCI2". On POSIX, the name of the device (e.g., "/dev/ttyS0")
Returns "(invalid)" if serial is invalid or not configured.
Parameters
[in] serial port
Returns
null-terminated string describing the serial port
int xbee_ser_putchar (xbee_serial_t * serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] ch character to send
Return values
0 Successfully sent (queued) character.
-ENOSPC The write buffer is full and the character wasn't sent.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References ENOSPC, and xbee_ser_write().
int xbee_ser_read (xbee_serial_t * serial, void FAR * buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
If there is no data available when the function is called, it will return immediately.
Parameters
[in] serial XBee serial port
[out] buffer buffer to hold bytes read from XBee serial port
[in] bufsize maximum number of bytes to read
Return values
>=0 The number of bytes read from XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_write(), xbee_ser_putchar(), xbee_ser_getchar()
References EINVAL, xbee_cbuf_free(), xbee_cbuf_get(), and xbee_ser_set_rts().
int xbee_ser_rx_flush (xbee_serial_t * serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_used()
References xbee_cbuf_flush().
int xbee_ser_rx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial receive buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_used(), xbee_ser_rx_flush()
References xbee_cbuf_free().
int xbee_ser_rx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
>=0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_flush()
Note
Unlike xbee_ser_tx_used(), this function MUST return the number of bytes available. Some layers of the library wait until enough bytes are ready before continuing.
We may expand on or replace this API. On some platforms (like Win32) we have to do some of our own buffering in order to peek at data in the serial receive buffer. Most of the driver only requires a check to see if some number of bytes are available or not. Consider changing the API to something like:
 int xbee_ser_rx_avail( xbee_serial_t *serial, uint8_t count)
returns TRUE if count bytes are available, FALSE otherwise.
References xbee_cbuf_used().
int xbee_ser_set_rts (xbee_serial_t * serial, bool_t asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
Typically used to enter the XBee device's boot loader and initiate a firmware update.
Parameters
[in] serial XBee serial port
[in] asserted Set to 1 to assert RTS (ok for XBee to send to us) or 0 to deassert RTS (tell XBee not to send to us).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_get_cts()
References EINVAL.
Referenced by xbee_ser_flowcontrol(), xbee_ser_getchar(), and xbee_ser_read().
int xbee_ser_tx_flush (xbee_serial_t * serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_used()
int xbee_ser_tx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_used(), xbee_ser_tx_flush()
int xbee_ser_tx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 The buffer size is unlimited (or space used is unknown).
>0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_flush()
int xbee_ser_write (xbee_serial_t * serial, const void FAR * buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] buffer source of bytes to send
[in] length number of bytes to write
Return values
>=0 The number of bytes successfully written to XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_read(), xbee_ser_putchar(), xbee_ser_getchar()
References EINVAL, and FAR.
Referenced by xbee_ser_putchar().