Digi XBee(R) ANSI C Host Library: HAL: Win32/MinGW/gcc
HAL: Win32/MinGW/gcc
Hardware Abstraction Layer (HAL)
32-bit Windows (Win32) using MinGW and gcc.
Files
file platform_config.h
This file is automatically included by xbee/platform.h.
file xbee_platform_win32.c
Platform-specific functions for use by the XBee Driver on Win32/gcc target.
file xbee_readline.c
ANSI C xbee_readline() implementation for Win32.
file xbee_serial_win32.c
Serial Interface for XBee Module (Win32 Platform)
Data Structures
struct xbee_serial_t
Macros
#define strcmpi strcasecmp
#define strncmpi strncasecmp
#define PACKED_STRUCT struct __attribute__ ((__packed__, __gcc_struct__))
#define XBEE_PACKED(name, decl) PACKED_STRUCT name decl
#define _f_memcpy memcpy
#define _f_memset memset
#define XBEE_WIFI_ENABLED 1
#define XBEE_CELLULAR_ENABLED 1
#define XBEE_NATIVE_64BIT
#define XBEE_SER_TX_BUFSIZE 2048
#define XBEE_SER_RX_BUFSIZE 4096
#define XBEE_SERIAL_MAX_BAUDRATE 921600
#define ZCL_TIME_EPOCH_DELTA ZCL_TIME_EPOCH_DELTA_1970
#define XBEE_MS_TIMER_RESOLUTION 16
#define XBEE_READLINE_STATE_INIT 0
#define XBEE_READLINE_STATE_START_LINE 1
#define XBEE_READLINE_STATE_CONTINUE_LINE 2
#define XBEE_READLINE_STATE_EOF -1
#define XBEE_SER_CHECK(ptr) do { if (xbee_ser_invalid(ptr)) return -EINVAL; } while (0)
Typedefs
typedef int bool_t
Functions
uint32_t xbee_seconds_timer ()
Platform-specific function to return the number of elapsed seconds.
uint32_t xbee_millisecond_timer ()
Platform-specific function to return the number of elapsed milliseconds.
int xbee_readline (char *buffer, int length)
This function is a non-blocking version of gets(), used to read a line of input from the user.
int xbee_ser_invalid (xbee_serial_t *serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
const char * xbee_ser_portname (xbee_serial_t *serial)
Returns a human-readable string describing the serial port.
int xbee_ser_write (xbee_serial_t *serial, const void FAR *buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
int xbee_ser_read (xbee_serial_t *serial, void FAR *buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
int xbee_ser_putchar (xbee_serial_t *serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
int xbee_ser_getchar (xbee_serial_t *serial)
Reads a single character from the XBee serial port serial.
int xbee_ser_tx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_flush (xbee_serial_t *serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
int xbee_ser_rx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_flush (xbee_serial_t *serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
int xbee_ser_baudrate (xbee_serial_t *serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
int xbee_ser_open (xbee_serial_t *serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
int xbee_ser_close (xbee_serial_t *serial)
Close the serial port attached to XBee serial port serial.
int xbee_ser_break (xbee_serial_t *serial, int enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
int xbee_ser_flowcontrol (xbee_serial_t *serial, int enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
int xbee_ser_set_rts (xbee_serial_t *serial, int asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
int xbee_ser_get_cts (xbee_serial_t *serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Detailed Description
32-bit Windows (Win32) using MinGW and gcc.
Function Documentation
uint32_t xbee_millisecond_timer (void)
Platform-specific function to return the number of elapsed milliseconds.
OK for this counter to rollover. Used for timing and should have a resolution of at least 60ms.
Rabbit has 1ms resolution.
HCS08 has 4ms resolution.
DOS has 18 ticks/second (55.55ms resolution)
(Function name wrapped in parentheses so platforms can use a macro function of the same name.)
Returns
Number of elapsed milliseconds.
See also
XBEE_MS_TIMER_RESOLUTION
int xbee_readline (char * buffer, int length)
This function is a non-blocking version of gets(), used to read a line of input from the user.
It waits for a string from stdin terminated by a return. It should be called repeatedly, until it returns a value other than -EAGAIN. The input string, stored in buffer is null-terminated without the return.
The user should make sure only one process calls this function at a time.
Parameters
[in,out] buffer buffer to store input from user
[in] length size of buffer
Return values
>=0 User ended the input with a newline, return value is number of bytes written.
-EAGAIN User has not completed a line.
-EINVAL NULL buffer or length is less than 1.
-ENODATA User entered CTRL-D to end input.
References EAGAIN, EINVAL, and ENODATA.
uint32_t xbee_seconds_timer (void)
Platform-specific function to return the number of elapsed seconds.
On some platforms, this is the equivalent of an "uptime".
On other platforms, it may reflect the value of the RTC, which might not be synchronized with a time server and might include leap seconds.
Regardless, it should consistently report elapsed time and not jump on clock synchronization.
In addition to determining timeouts, the ZCL Time Cluster makes use of it to report current time.
(Function name wrapped in parentheses so platforms can use a macro function of the same name.)
Returns
Number of elapsed seconds.
int xbee_ser_baudrate (xbee_serial_t * serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_open(), xbee_ser_close(), xbee_ser_break()
References EINVAL, EIO, and PRIu32.
Referenced by xbee_ser_open().
int xbee_ser_break (xbee_serial_t * serial, int enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
Parameters
[in] serial XBee serial port
[in] enabled Set to 1 to start the break or 0 to end the break (and resume transmitting).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_close()
References EIO.
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_close (xbee_serial_t * serial)
Close the serial port attached to XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 closed serial port
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_baudrate(), xbee_ser_break()
int xbee_ser_flowcontrol (xbee_serial_t * serial, int enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] enabled Set to 0 to disable flow control or non-zero to enable flow control.
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_set_rts(), xbee_ser_get_cts()
References EIO.
Referenced by xbee_dev_init(), xbee_fw_install_ebl_tick(), xbee_fw_install_oem_tick(), and xbee_ser_set_rts().
int xbee_ser_get_cts (xbee_serial_t * serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Note that this function doesn't return the value of the pin – it returns whether it's asserted (i.e., clear to send to the XBee serial port) or not.
Parameters
[in] serial XBee serial port
Return values
1 it's clear to send
0 it's not clear to send
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_set_rts()
References EIO.
Referenced by xbee_bl_gen3_install_tick(), and xbee_frame_write().
int xbee_ser_getchar (xbee_serial_t * serial)
Reads a single character from the XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0-255 character read from XBee serial port
-ENODATA There aren't any characters in the read buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References ENODATA, and xbee_ser_read().
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_invalid (xbee_serial_t * serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
Confirms that it is non-NULL and is set to a valid port.
Parameters
[in] serial XBee serial port
Return values
1 serial is not a valid XBee serial port
0 serial is a valid XBee serial port
Referenced by _xbee_frame_load(), and xbee_frame_write().
int xbee_ser_open (xbee_serial_t * serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_baudrate(), xbee_ser_close(), xbee_ser_break()
References EINVAL, EIO, and xbee_ser_baudrate().
Referenced by xbee_bl_gen3_install_tick(), xbee_dev_init(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
const char* xbee_ser_portname (xbee_serial_t * serial)
Returns a human-readable string describing the serial port.
For example, on a Windows machine this will be "COM1" or "COM999". On a Rabbit, it will be a single letter, "A" through "F". On Freescale HCS08, it will be something like "SCI1" or "SCI2". On POSIX, the name of the device (e.g., "/dev/ttyS0")
Returns "(invalid)" if serial is invalid or not configured.
Parameters
[in] serial port
Returns
null-terminated string describing the serial port
Referenced by xbee_dev_dump_settings().
int xbee_ser_putchar (xbee_serial_t * serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] ch character to send
Return values
0 Successfully sent (queued) character.
-ENOSPC The write buffer is full and the character wasn't sent.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References ENOSPC, and xbee_ser_write().
Referenced by xbee_bl_gen3_install_state(), xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_read (xbee_serial_t * serial, void FAR * buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
If there is no data available when the function is called, it will return immediately.
Parameters
[in] serial XBee serial port
[out] buffer buffer to hold bytes read from XBee serial port
[in] bufsize maximum number of bytes to read
Return values
>=0 The number of bytes read from XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_write(), xbee_ser_putchar(), xbee_ser_getchar()
References EAGAIN, EINVAL, EIO, hex_dump(), and HEX_DUMP_FLAG_TAB.
Referenced by _xbee_frame_load(), xbee_bl_gen3_install_tick(), xbee_fw_install_oem_tick(), and xbee_ser_getchar().
int xbee_ser_rx_flush (xbee_serial_t * serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_used()
Referenced by xbee_bl_gen3_install_state(), xbee_bl_gen3_install_tick(), and xbee_fw_install_ebl_tick().
int xbee_ser_rx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial receive buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_used(), xbee_ser_rx_flush()
References xbee_ser_rx_used().
int xbee_ser_rx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
>=0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_flush()
Note
Unlike xbee_ser_tx_used(), this function MUST return the number of bytes available. Some layers of the library wait until enough bytes are ready before continuing.
We may expand on or replace this API. On some platforms (like Win32) we have to do some of our own buffering in order to peek at data in the serial receive buffer. Most of the driver only requires a check to see if some number of bytes are available or not. Consider changing the API to something like:
 int xbee_ser_rx_avail( xbee_serial_t *serial, uint8_t count)
returns TRUE if count bytes are available, FALSE otherwise.
Referenced by xbee_bl_gen3_install_tick(), and xbee_ser_rx_free().
int xbee_ser_set_rts (xbee_serial_t * serial, int asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
Typically used to enter the XBee device's boot loader and initiate a firmware update.
Parameters
[in] serial XBee serial port
[in] asserted Set to 1 to assert RTS (ok for XBee to send to us) or 0 to deassert RTS (tell XBee not to send to us).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_get_cts()
References EIO, and xbee_ser_flowcontrol().
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_tx_flush (xbee_serial_t * serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_used()
Referenced by xbee_fw_install_ebl_tick().
int xbee_ser_tx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_used(), xbee_ser_tx_flush()
References xbee_ser_tx_used().
Referenced by xbee_bl_gen3_install_state(), xbee_frame_write(), and xbee_fw_install_oem_tick().
int xbee_ser_tx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 The buffer size is unlimited (or space used is unknown).
>0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_flush()
Referenced by xbee_frame_write(), and xbee_ser_tx_free().
int xbee_ser_write (xbee_serial_t * serial, const void FAR * buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] buffer source of bytes to send
[in] length number of bytes to write
Return values
>=0 The number of bytes successfully written to XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_read(), xbee_ser_putchar(), xbee_ser_getchar()
References EINVAL, EIO, hex_dump(), and HEX_DUMP_FLAG_TAB.
Referenced by xbee_bl_gen3_install_state(), xbee_frame_write(), xbee_fw_install_oem_tick(), and xbee_ser_putchar().