Digi XBee(R) ANSI C Host Library: Utility/Support Code
Utility/Support Code
Modules
XMODEM (send-only)
Xmodem API used with firmware updates.
Byte-swapping functions
Macros for converting between big/little endian and host byte order.
Circular Buffer
Circular buffer data type used by the OTA (Over-The-Air) firmware update client and transparent serial cluster.
Portable time functions
Portable time functions using January 1, 2000 as the epoch.
Files
file hexdump.c
ANSI C hex_dump() implementation if not available natively on a given platform.
file hexstrtobyte.c
ANSI C hexstrtobyte() implementation if not available natively on a given platform.
Functions
void hex_dump (const void FAR *address, uint16_t length, uint16_t flags)
Helper function for printing a hex dump of memory to stdout.
int hexstrtobyte (const char *p)
Detailed Description
Function Documentation
void hex_dump (const void FAR * address, uint16_t length, uint16_t flags)
Helper function for printing a hex dump of memory to stdout.
A reference implementation is provided in as util/hexdump.c. Dumps data in hex/printable format, 16 bytes to a line, to stdout.
Parameters
[in] address Address of data to dump.
[in] length Number of bytes to dump.
[in] flags One of
HEX_DUMP_FLAG_NONE
HEX_DUMP_FLAG_OFFSET
HEX_DUMP_FLAG_ADDRESS
HEX_DUMP_FLAG_TAB
References FAR, HEX_DUMP_FLAG_ADDRESS, HEX_DUMP_FLAG_OFFSET, HEX_DUMP_FLAG_TAB, and PRIpFAR.
Referenced by _pxbee_ota_transparent_rx(), _sxa_disc_process_node_data(), _sxa_io_process_response(), _xbee_frame_dispatch(), _xbee_frame_load(), _zcl_send_read_from_zdo_match(), _zcl_write_attributes(), _zdo_active_ep_respond(), _zdo_match_desc_respond(), wpan_envelope_dump(), xbee_cmd_send(), xbee_ipv4_envelope_dump(), xbee_ser_read(), xbee_ser_write(), zcl_command_dump(), zcl_envelope_payload_dump(), zcl_general_command(), zcl_identify_command(), zcl_ota_upgrade_cluster_handler(), zcl_print_attribute_value(), zcl_time_client(), zdo_handler(), and zdo_send_response().