Digi XBee(R) ANSI C Host Library: Transparent Serial Cluster
Transparent Serial Cluster
XBee Interface » Digi Data Endpoint
    Support code for Transparent Serial Cluster of Digi Data Endpoint
Files
file transparent_serial.h
Support code for the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
file xbee_transparent_serial.c
Support code for the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
Functions
int xbee_transparent_serial (wpan_envelope_t *envelope)
Send data to the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
int xbee_transparent_serial_str (wpan_envelope_t *envelope, const char FAR *data)
Send string to the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
Detailed Description
    Support code for Transparent Serial Cluster of Digi Data Endpoint
Function Documentation
int xbee_transparent_serial (wpan_envelope_t * envelope)
Send data to the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
Parameters
[in,out] envelope Envelope with device, addresses, payload, length and options filled in. This function sets the profile, endpoints, and cluster fields of the envelope.
Return values
0 data sent
!0 error trying to send request
See also
xbee_transparent_serial_str
Note
This is a preliminary API and may change in a future release.
References wpan_envelope_t::cluster_id, wpan_envelope_t::dest_endpoint, DIGI_CLUST_SERIAL, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, WPAN_ENDPOINT_DIGI_DATA, wpan_envelope_send(), and WPAN_PROFILE_DIGI.
Referenced by _pxbee_ota_xmodem_write(), and xbee_transparent_serial_str().
int xbee_transparent_serial_str (wpan_envelope_t * envelope, const char FAR * data)
Send string to the "Digi Transparent Serial" cluster (cluster 0x0011 of endpoint 0xE8).
Parameters
[in,out] envelope Envelope with device, addresses and options filled in. This function sets the payload, length, profile, endpoints, and cluster fields of the envelope.
[in] data string to send
Return values
0 data sent
!0 error trying to send request
See also
xbee_transparent_serial
Note
This is a preliminary API and may change in a future release.
References wpan_envelope_t::length, wpan_envelope_t::payload, and xbee_transparent_serial().