Digi XBee(R) ANSI C Host Library: Serial Interface
Serial Interface
XBee Interface
Files
file serial.h
Platform-specific layer provieds a consistent serial API to upper layers of the driver.
Functions
bool_t xbee_ser_invalid (xbee_serial_t *serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
const char * xbee_ser_portname (xbee_serial_t *serial)
Returns a human-readable string describing the serial port.
int xbee_ser_write (xbee_serial_t *serial, const void FAR *buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
int xbee_ser_read (xbee_serial_t *serial, void FAR *buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
int xbee_ser_putchar (xbee_serial_t *serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
int xbee_ser_getchar (xbee_serial_t *serial)
Reads a single character from the XBee serial port serial.
int xbee_ser_tx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
int xbee_ser_tx_flush (xbee_serial_t *serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
int xbee_ser_rx_free (xbee_serial_t *serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_used (xbee_serial_t *serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
int xbee_ser_rx_flush (xbee_serial_t *serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
int xbee_ser_open (xbee_serial_t *serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
int xbee_ser_baudrate (xbee_serial_t *serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
int xbee_ser_close (xbee_serial_t *serial)
Close the serial port attached to XBee serial port serial.
int xbee_ser_break (xbee_serial_t *serial, bool_t enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
int xbee_ser_flowcontrol (xbee_serial_t *serial, bool_t enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
int xbee_ser_set_rts (xbee_serial_t *serial, bool_t asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
int xbee_ser_get_cts (xbee_serial_t *serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Detailed Description
Function Documentation
int xbee_ser_baudrate (xbee_serial_t * serial, uint32_t baudrate)
Change the baud rate of XBee serial port serial to baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_open(), xbee_ser_close(), xbee_ser_break()
References EINVAL, EIO, PRIu32, UART_DLL, UART_DLM, UART_LCR, xbee_cbuf_putch(), and xbee_ser_invalid().
Referenced by xbee_ser_open().
int xbee_ser_break (xbee_serial_t * serial, bool_t enabled)
Disable the serial transmit pin and pull it low to send a break to the XBee serial port.
Parameters
[in] serial XBee serial port
[in] enabled Set to 1 to start the break or 0 to end the break (and resume transmitting).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_close()
References EINVAL, EIO, UART_LCR, and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_close (xbee_serial_t * serial)
Close the serial port attached to XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 closed serial port
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_open(), xbee_ser_baudrate(), xbee_ser_break()
References EINVAL, UART_IER, UART_MCR, xbee_ser_invalid(), xbee_ser_rx_flush(), and xbee_ser_tx_flush().
Referenced by xbee_ser_open().
int xbee_ser_flowcontrol (xbee_serial_t * serial, bool_t enabled)
Enable or disable hardware flow control (CTS/RTS) on the serial port for XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] enabled Set to 0 to disable flow control or non-zero to enable flow control.
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_set_rts(), xbee_ser_get_cts()
References EINVAL, EIO, UART_MCR, xbee_cbuf_free(), xbee_ser_invalid(), and xbee_ser_set_rts().
Referenced by xbee_dev_init(), xbee_fw_install_ebl_tick(), xbee_fw_install_oem_tick(), and xbee_ser_set_rts().
int xbee_ser_get_cts (xbee_serial_t * serial)
Read the status of the /CTS (clear to send) pin on the serial port connected to XBee serial port serial.
Note that this function doesn't return the value of the pin – it returns whether it's asserted (i.e., clear to send to the XBee serial port) or not.
Parameters
[in] serial XBee serial port
Return values
1 it's clear to send
0 it's not clear to send
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_set_rts()
References EINVAL, EIO, UART_MSR, xbee_cbuf_putch(), and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_tick(), and xbee_frame_write().
int xbee_ser_getchar (xbee_serial_t * serial)
Reads a single character from the XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0-255 character read from XBee serial port
-ENODATA There aren't any characters in the read buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References EINVAL, ENODATA, xbee_cbuf_free(), xbee_cbuf_getch(), xbee_ser_invalid(), xbee_ser_read(), and xbee_ser_set_rts().
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_invalid (xbee_serial_t * serial)
Helper function used by other xbee_serial functions to validate the serial parameter.
Confirms that it is non-NULL and is set to a valid port.
Parameters
[in] serial XBee serial port
Return values
1 serial is not a valid XBee serial port
0 serial is a valid XBee serial port
Referenced by _xbee_frame_load(), xbee_frame_write(), xbee_ser_baudrate(), xbee_ser_break(), xbee_ser_close(), xbee_ser_flowcontrol(), xbee_ser_get_cts(), xbee_ser_getchar(), xbee_ser_open(), xbee_ser_putchar(), xbee_ser_read(), xbee_ser_rx_flush(), xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_tx_flush(), xbee_ser_tx_free(), xbee_ser_tx_used(), and xbee_ser_write().
int xbee_ser_open (xbee_serial_t * serial, uint32_t baudrate)
Opens the serial port connected to XBee serial port serial at baudrate bits/second.
Parameters
[in] serial XBee serial port
[in] baudrate Bits per second of serial data transfer speed.
Return values
0 Opened serial port within 5% of requested baudrate.
-EINVAL serial is not a valid XBee serial port.
-EIO Can't open serial port within 5% of requested baudrate.
See also
xbee_ser_baudrate(), xbee_ser_close(), xbee_ser_break()
References EINVAL, EIO, PRIu32, UART_FCR, UART_IER, UART_LCR, UART_LSR, UART_MCR, UART_MSR, UART_RBR, xbee_cbuf_init(), xbee_ser_baudrate(), xbee_ser_close(), and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_tick(), xbee_dev_init(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
const char * xbee_ser_portname (xbee_serial_t * serial)
Returns a human-readable string describing the serial port.
For example, on a Windows machine this will be "COM1" or "COM999". On a Rabbit, it will be a single letter, "A" through "F". On Freescale HCS08, it will be something like "SCI1" or "SCI2". On POSIX, the name of the device (e.g., "/dev/ttyS0")
Returns "(invalid)" if serial is invalid or not configured.
Parameters
[in] serial port
Returns
null-terminated string describing the serial port
Referenced by xbee_dev_dump_settings().
int xbee_ser_putchar (xbee_serial_t * serial, uint8_t ch)
Transmits a single character, ch, to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] ch character to send
Return values
0 Successfully sent (queued) character.
-ENOSPC The write buffer is full and the character wasn't sent.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_read(), xbee_ser_write(), xbee_ser_getchar()
References EINVAL, EIO, ENOSPC, xbee_cbuf_putch(), xbee_ser_invalid(), and xbee_ser_write().
Referenced by xbee_bl_gen3_install_state(), xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_fw_install_oem_tick().
int xbee_ser_read (xbee_serial_t * serial, void FAR * buffer, int bufsize)
Reads up to bufsize bytes from XBee serial port serial and into buffer.
If there is no data available when the function is called, it will return immediately.
Parameters
[in] serial XBee serial port
[out] buffer buffer to hold bytes read from XBee serial port
[in] bufsize maximum number of bytes to read
Return values
>=0 The number of bytes read from XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_write(), xbee_ser_putchar(), xbee_ser_getchar()
References EAGAIN, EINVAL, EIO, hex_dump(), HEX_DUMP_FLAG_NONE, HEX_DUMP_FLAG_TAB, xbee_cbuf_free(), xbee_cbuf_get(), xbee_cbuf_used(), xbee_ser_invalid(), and xbee_ser_set_rts().
Referenced by _xbee_frame_load(), xbee_bl_gen3_install_tick(), xbee_fw_install_oem_tick(), and xbee_ser_getchar().
int xbee_ser_rx_flush (xbee_serial_t * serial)
Deletes all characters in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_used()
References EINVAL, INTERRUPT_DISABLE, INTERRUPT_ENABLE, UART_FCR, UART_LSR, UART_RBR, xbee_cbuf_flush(), and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_state(), xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), and xbee_ser_close().
int xbee_ser_rx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial receive buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_used(), xbee_ser_rx_flush()
References EINVAL, xbee_cbuf_free(), xbee_ser_invalid(), and xbee_ser_rx_used().
int xbee_ser_rx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial receive buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
>=0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_tx_free(), xbee_ser_tx_used(), xbee_ser_tx_flush(), xbee_ser_rx_free(), xbee_ser_rx_flush()
Note
Unlike xbee_ser_tx_used(), this function MUST return the number of bytes available. Some layers of the library wait until enough bytes are ready before continuing.
We may expand on or replace this API. On some platforms (like Win32) we have to do some of our own buffering in order to peek at data in the serial receive buffer. Most of the driver only requires a check to see if some number of bytes are available or not. Consider changing the API to something like:
 int xbee_ser_rx_avail( xbee_serial_t *serial, uint8_t count)
returns TRUE if count bytes are available, FALSE otherwise.
References EINVAL, xbee_cbuf_used(), and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_tick(), and xbee_ser_rx_free().
int xbee_ser_set_rts (xbee_serial_t * serial, bool_t asserted)
Disable hardware flow control and manually set the RTS (ready to send) pin on the XBee device's serial port.
Typically used to enter the XBee device's boot loader and initiate a firmware update.
Parameters
[in] serial XBee serial port
[in] asserted Set to 1 to assert RTS (ok for XBee to send to us) or 0 to deassert RTS (tell XBee not to send to us).
Return values
0 Success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_flowcontrol(), xbee_ser_get_cts()
References EINVAL, EIO, UART_MCR, and xbee_ser_flowcontrol().
Referenced by xbee_bl_gen3_install_tick(), xbee_fw_install_ebl_tick(), xbee_fw_install_oem_tick(), xbee_ser_flowcontrol(), xbee_ser_getchar(), and xbee_ser_read().
int xbee_ser_tx_flush (xbee_serial_t * serial)
Flushes (i.e., deletes and does not transmit) characters in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 success
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_used()
References EINVAL, INTERRUPT_DISABLE, INTERRUPT_ENABLE, UART_FCR, UART_IER, xbee_cbuf_flush(), and xbee_ser_invalid().
Referenced by xbee_fw_install_ebl_tick(), and xbee_ser_close().
int xbee_ser_tx_free (xbee_serial_t * serial)
Returns the number of bytes of unused space in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
INT_MAX The buffer size is unlimited (or unknown).
>=0 The number of bytes it would take to fill the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_used(), xbee_ser_tx_flush()
References EINVAL, xbee_cbuf_free(), xbee_ser_invalid(), and xbee_ser_tx_used().
Referenced by xbee_bl_gen3_install_state(), xbee_frame_write(), and xbee_fw_install_oem_tick().
int xbee_ser_tx_used (xbee_serial_t * serial)
Returns the number of queued bytes in the serial transmit buffer for XBee serial port serial.
Parameters
[in] serial XBee serial port
Return values
0 The buffer size is unlimited (or space used is unknown).
>0 The number of bytes queued in the XBee serial port's serial transmit buffer.
-EINVAL serial is not a valid XBee serial port.
See also
xbee_ser_rx_free(), xbee_ser_rx_used(), xbee_ser_rx_flush(), xbee_ser_tx_free(), xbee_ser_tx_flush()
References EINVAL, xbee_cbuf_used(), and xbee_ser_invalid().
Referenced by xbee_frame_write(), and xbee_ser_tx_free().
int xbee_ser_write (xbee_serial_t * serial, const void FAR * buffer, int length)
Transmits length bytes from buffer to the XBee serial port serial.
Parameters
[in] serial XBee serial port
[in] buffer source of bytes to send
[in] length number of bytes to write
Return values
>=0 The number of bytes successfully written to XBee serial port.
-EINVAL serial is not a valid XBee serial port.
-EIO I/O error attempting to write to serial port.
See also
xbee_ser_read(), xbee_ser_putchar(), xbee_ser_getchar()
References EINVAL, EIO, FAR, hex_dump(), HEX_DUMP_FLAG_TAB, INTERRUPT_DISABLE, INTERRUPT_ENABLE, UART_IER, UART_LSR, UART_THR, xbee_cbuf_free(), xbee_cbuf_getch(), xbee_cbuf_put(), and xbee_ser_invalid().
Referenced by xbee_bl_gen3_install_state(), xbee_frame_write(), xbee_fw_install_oem_tick(), and xbee_ser_putchar().