/*
 * Copyright (c) 2019 Digi International Inc.,
 * All rights not expressly granted are reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Digi International Inc., 9350 Excelsior Blvd., Suite 700, Hopkins, MN 55343
 * ===========================================================================
 */

// Modified code generated by crcany: https://github.com/madler/crcany

// The _bit, _byte, and _word routines return the CRC of the len bytes at mem,
// applied to the previous CRC value, crc. If mem is NULL, then the other
// arguments are ignored, and the initial CRC, i.e. the CRC of zero bytes, is
// returned. Those routines will all return the same result, differing only in
// speed and code complexity.

#include "xbee/platform.h"

// Compute the CRC a bit at a time.
uint16_t crc16buypass_bit(uint16_t crc, void const *mem, size_t len);

// Compute the CRC a byte at a time.
uint16_t crc16buypass_byte(uint16_t crc, void const *mem, size_t len);
